"""initial

Revision ID: 80190a0f9418
Revises: 
Create Date: 2020-07-02 09:27:14.070602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80190a0f9418'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('classification', sa.String(length=32), nullable=True),
    sa.Column('plain', sa.Boolean(), nullable=True),
    sa.Column('trebledodging', sa.Boolean(), nullable=True),
    sa.Column('little', sa.Boolean(), nullable=True),
    sa.Column('differential', sa.Boolean(), nullable=True),
    sa.Column('lengthoflead', sa.Integer(), nullable=True),
    sa.Column('numberofhunts', sa.Integer(), nullable=True),
    sa.Column('huntbellpath', sa.String(length=32), nullable=True),
    sa.Column('methodset_notes', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('leadhead', sa.String(length=32), nullable=True),
    sa.Column('leadheadcode', sa.String(length=32), nullable=True),
    sa.Column('symmetry', sa.String(length=32), nullable=True),
    sa.Column('notation', sa.String(length=128), nullable=True),
    sa.Column('falseness', sa.String(length=32), nullable=True),
    sa.Column('extensionconstruction', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.String(length=128), nullable=True),
    sa.Column('pmmref', sa.String(length=32), nullable=True),
    sa.Column('bnref', sa.String(length=32), nullable=True),
    sa.Column('cbref', sa.String(length=32), nullable=True),
    sa.Column('rwref', sa.String(length=32), nullable=True),
    sa.Column('tdmmref', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_methods_name'), 'methods', ['name'], unique=False)
    op.create_index(op.f('ix_methods_title'), 'methods', ['title'], unique=True)
    op.create_table('performances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('society', sa.String(length=32), nullable=True),
    sa.Column('town', sa.String(length=32), nullable=True),
    sa.Column('county', sa.String(length=32), nullable=True),
    sa.Column('building', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('room', sa.String(length=32), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('method_id_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['method_id_fk'], ['methods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performances')
    op.drop_index(op.f('ix_methods_title'), table_name='methods')
    op.drop_index(op.f('ix_methods_name'), table_name='methods')
    op.drop_table('methods')
    # ### end Alembic commands ###
